<script setup lang="ts">
import { computed } from 'vue'
import { BaseEdge, getBezierPath, type EdgeProps } from '@vue-flow/core'

const props = defineProps<EdgeProps>()

const pathHandler = computed(() => getBezierPath(props))

</script>

<template>
  <!-- Base Edge Path (Static Background) -->
  <BaseEdge
    :path="pathHandler[0]"
    :style="{ stroke: '#333', strokeWidth: 2 }"
  />

  <!-- Animated Overlay Path -->
  <BaseEdge
    class="animated-edge"
    :path="pathHandler[0]"
    :style="{
        strokeWidth: 2,
        stroke: 'url(#gradient-edge)',
        opacity: 0.8
    }"
  />

  <!-- SVG Definition for Gradient (Needs to be injected somewhere global usually, but putting here for scope) -->
  <!-- Note: In VueFlow,defs should ideally be in the main SVG or a dedicated Defs component,
       but for simplicity/portability we can try inline or rely on CSS animations on stroke-dasharray -->

</template>

<style>
/* Unscoped style to target the SVG elements generated by BaseEdge if needed */
.animated-edge {
  stroke-dasharray: 10;
  animation: flowAnimation 1s linear infinite;
  /* Fallback color if gradient fails context */
  stroke: #f39c12;
}

@keyframes flowAnimation {
  from {
    stroke-dashoffset: 20;
  }
  to {
    stroke-dashoffset: 0;
  }
}
</style>
